#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'appendAndDelete' function below.
#
# The function is expected to return a STRING.
# The function accepts following parameters:
#  1. STRING s
#  2. STRING t
#  3. INTEGER k
#

def appendAndDelete(s, t, k):
    min_len = min(len(s), len(t))
    i = 0
    while s[i] == t[i]:
        i+=1
        if i == min_len:
            break
    diff = len(s) + len(t) - 2*i
    if len(s) + len(t) <= k:
        return 'Yes'
    elif diff > k:
        return 'No'
    else:
        return 'Yes' if (k-diff)%2 == 0 else 'No'
    # Write your code here

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    s = input()

    t = input()

    k = int(input().strip())

    result = appendAndDelete(s, t, k)

    fptr.write(result + '\n')

    fptr.close()
